#!/bin/sh
ROOT=$PWD

dumpRoot()
{
	echo 'all:' 									> Makefile
	echo '	cd ./build && make && cp exec ../' 		>> Makefile
	echo 'clean:' 									>> Makefile
	echo '	cd ./build && make clean' 				>> Makefile
}

dumpBuild()
{
	echo 'MODULES = $(wildcard *.c)' 											> build/Makefile
	echo 'OBJS = $(patsubst %.c, %.o, $(MODULES))' 								>> build/Makefile                        
	echo 'LINK_HEAD = -I/usr/local/include/monkc -I/usr/local/include/lemontea' >> build/Makefile    
	echo 'LINK_BIN = -lpthread -L/usr/local/lib -lmonkc -llemontea' 			>> build/Makefile
	echo 'CC = clang -g -w -Wall -Wno-unused-variable -Wno-return-type' 		>> build/Makefile             
	echo 'AS = as' 																>> build/Makefile
	echo 'LEX = mcpp' 															>> build/Makefile                                               
	echo 'exec:$(OBJS)' 														>> build/Makefile
	echo '	$(CC) -o exec $(OBJS) $(LINK_BIN)' 									>> build/Makefile
	echo '%.o:%.c' 																>> build/Makefile
	echo '	$(LEX) $< .hash' 													>> build/Makefile
	echo '	mv -f .hash $<' 													>> build/Makefile
	echo '	$(CC) -c $< $(LINK_HEAD)' 											>> build/Makefile                                             
	echo 'clean:' 																>> build/Makefile
	echo '	rm -f exec $(OBJS) temp.* stream.txt core'							>> build/Makefile
	echo 'dump:'																>> build/Makefile
	echo '	ulimit -c unlimited'												>> build/Makefile
}

if [ "$1" = "" ]
then
	echo "mcbuild -create			//create a project at current path"
	echo "mcbuild -build 			//build a project"
	echo "mcbuild -clean            //clean a project"
fi
if [ "$1" = "-create" ]
then
	echo "create a project"
	mkdir -p -v build
	mkdir -p -v src
	dumpRoot
	dumpBuild
fi
if [ "$1" = "-build" ]
then
	echo "CLEAN AND BUILD..."
	rm -r build	
	mkdir -p -v build
	dumpRoot
	dumpBuild
	cp -f $(find ./src -name '*.c') ./build
	cp -f $(find ./src -name '*.h') ./build
	cp -f $(find ./src -name '*.p') ./build
	make && echo "BUILD SUCCESS"
fi
if [ "$1" = "-clean" ]
then
	echo "CLEAN..."
	rm -f exec core
	rm -f -r build
	mkdir -p -v build
	dumpRoot
	dumpBuild
fi
